// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/nqtinh/go-gin-project/models"
)

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// CreateUserTransaction mocks base method.
func (m *MockTransactionService) CreateUserTransaction(ctx context.Context, req *models.CreateUserTransactionReq) (*models.UserTransactionResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTransaction", ctx, req)
	ret0, _ := ret[0].(*models.UserTransactionResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTransaction indicates an expected call of CreateUserTransaction.
func (mr *MockTransactionServiceMockRecorder) CreateUserTransaction(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTransaction", reflect.TypeOf((*MockTransactionService)(nil).CreateUserTransaction), ctx, req)
}

// DeleteTransactionByID mocks base method.
func (m *MockTransactionService) DeleteTransactionByID(ctx context.Context, transactionID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransactionByID", ctx, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransactionByID indicates an expected call of DeleteTransactionByID.
func (mr *MockTransactionServiceMockRecorder) DeleteTransactionByID(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransactionByID", reflect.TypeOf((*MockTransactionService)(nil).DeleteTransactionByID), ctx, transactionID)
}

// DeleteUserAccountTransactions mocks base method.
func (m *MockTransactionService) DeleteUserAccountTransactions(ctx context.Context, userID, accountID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAccountTransactions", ctx, userID, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAccountTransactions indicates an expected call of DeleteUserAccountTransactions.
func (mr *MockTransactionServiceMockRecorder) DeleteUserAccountTransactions(ctx, userID, accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAccountTransactions", reflect.TypeOf((*MockTransactionService)(nil).DeleteUserAccountTransactions), ctx, userID, accountID)
}

// DeleteUserTransactions mocks base method.
func (m *MockTransactionService) DeleteUserTransactions(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserTransactions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserTransactions indicates an expected call of DeleteUserTransactions.
func (mr *MockTransactionServiceMockRecorder) DeleteUserTransactions(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserTransactions", reflect.TypeOf((*MockTransactionService)(nil).DeleteUserTransactions), ctx, userID)
}

// GetUserTransactions mocks base method.
func (m *MockTransactionService) GetUserTransactions(ctx context.Context, req *models.GetUserTransactionsReq) ([]models.UserTransactionResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTransactions", ctx, req)
	ret0, _ := ret[0].([]models.UserTransactionResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTransactions indicates an expected call of GetUserTransactions.
func (mr *MockTransactionServiceMockRecorder) GetUserTransactions(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTransactions", reflect.TypeOf((*MockTransactionService)(nil).GetUserTransactions), ctx, req)
}

// UpdateUserAccountTransactions mocks base method.
func (m *MockTransactionService) UpdateUserAccountTransactions(ctx context.Context, req *models.UpdateUserAccountTransactionsReq) ([]models.UserTransactionResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAccountTransactions", ctx, req)
	ret0, _ := ret[0].([]models.UserTransactionResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserAccountTransactions indicates an expected call of UpdateUserAccountTransactions.
func (mr *MockTransactionServiceMockRecorder) UpdateUserAccountTransactions(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAccountTransactions", reflect.TypeOf((*MockTransactionService)(nil).UpdateUserAccountTransactions), ctx, req)
}

// UpdateUserTransactions mocks base method.
func (m *MockTransactionService) UpdateUserTransactions(ctx context.Context, req *models.UpdateUserTransactionsReq) ([]models.UserTransactionResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserTransactions", ctx, req)
	ret0, _ := ret[0].([]models.UserTransactionResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserTransactions indicates an expected call of UpdateUserTransactions.
func (mr *MockTransactionServiceMockRecorder) UpdateUserTransactions(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserTransactions", reflect.TypeOf((*MockTransactionService)(nil).UpdateUserTransactions), ctx, req)
}
